### ISSUE TITLE
parse_error

### ISSUE THREAD

**Issue by htakado** [komiyamma/hm_deepl_lang_translator#1]
64bit版を利用しています。
英語もしくは日本語を翻訳しようとしてマクロ実行すると以下のエラーがでます。
何か秀丸側で設定が必要、もしくは私の扱が間違っているのでしょうか？

"�|��G���[[json.exception.parse_error.101] parse error at line 1, column 1: syntax error while parsing value - unexpected end of input; expected '[', '{', or a literal"

**Comment by komiyamma** [comment]
利用しているのは、https://xn--pckzexbx21r8q9b.net/?page=nobu_tool_hm_deepl_lang_translator_cpp でしょうか？
エラーの内容からするに、$auth_key が機能していないように思えます。

https://xn--pckzexbx21r8q9b.net/?page=nobu_tool_hm_deepl_lang_translator_cpp のページ内容などを参照し
message($auth_key); などとして、正しくKEYが引けているか確認してみてください。

ローカルで確認してみた分では、64bit版でも機能していました。

**Comment by komiyamma** [comment]
さらにご自身のキーが使えるのかの確実なチェック方法としては、

https://api-free.deepl.com/v2/translate?auth_key=ここにご自身のAUTHキー&text=Apple&target_lang=ja

などとChromeなどでURL上で実行し、

{"translations":[{"detected_source_language":"EN","text":"アップル"}]}

などと結果として表示されれば、キーが機能しています。

**Comment by htakado** [comment]
お返事とご丁寧な確認方法ありがとうございます。

> 利用しているのは、https://xn--pckzexbx21r8q9b.net/?page=nobu_tool_hm_deepl_lang_translator_cpp でしょうか？
はい、これの64bit版になります。

> message($auth_key);
これを挿入してみましたが、登録したキーがポップアップされて正しく表示されました。
表示はダブルクォーテーション無しでした。

>  https://api-free.deepl.com/v2/translate?auth_key=ここにご自身のAUTHキー&text=Apple&target_lang=ja
こちらを実行すると、以下のように正しく表示されました。
　上記で表示された結果　→　{"translations":[{"detected_source_language":"EN","text":"アップル"}]}

ちなみにキーは以下のようにmacに記載してあります。
$auth_key = "44e0ac84-(省略)-f1bd7e3a731c:fx";

もし、上記以外で切り分ける方法がありましたらご教授いただけると幸甚です。

**Comment by komiyamma** [comment]
報告ありがとうございます。

$auth_key は正しいみたいですね。

エラーが意味するところは、
Deep-API(のURL)にアクセスした結果、
想定外の結果が返ってきているという意味です。

line 1 の column 1 すなわち最初の文字からしてすでに「非JSON」でエラーが出ており、
アクセス自体が拒否され、駄目だということを意味する別のHTMLページが表示されているか、
何かだと思われます。

他に考えられることだと、

- プロキシが間に挟まっているパターン
例えば会社などのネット環境だとすると、通常は間に「プロキシ」が挟んであって、
特定のブラウザではネットにアクセス出来ても、それ以外のプログラムからネットへのアクセスはコケる、
といった理由でしょうか。
一方、家庭のネット環境ということであれば、通常はプロキシは挟まっていないとは思います。

- ブロックの解除をしていないパターン
HmDeepLLangTranslatorCPP_x64.zip をダウンロードした際に
プロパティでブロックの解除をすることなく、普通にWindowsのエイスプローラーで解凍した
というパターンです。
（ただ、HmDeepLLangTranslatorCPPの場合、ブロック解除せずとも動作しているようには思えます...)

他は現段階ではパッとは思いつきません。

- やっている処理
結局は該当のURLにアクセスした結果、返ってきたテキスト全体を result だとして
そのテキストをJSONだと想定して、json_result["translations"][0]["text"] にアクセスする
といったことをやっているだけですので、
  ・ webにアクセス出来る
  ・  jsonが簡単に扱える
といったスクリプト言語等、使える環境であれば、
簡単にご自身でなんらかのスクリプトで制作できるかと思います。

- プロキシが間に挟まっているパターンかの確認
例えばpython版を流用して
(https://github.com/komiyamma/hm_deepl_lang_translator/blob/main/hm_deepl_lang_translator_py/HmDeepLLangTranslator.py)
```python
　from hmPython import hm 
```
の行を除去し、
プログラムの末尾の行に
```python
answer = TranslateByPost("AUTHキーの文字列", "Apple", "en", "ja") 
```
　などと付け足して普通のpythonから
```cmd
python HmDeepLLangTranslator.py
```
が動作する環境なのかどうか。
などでチェックできるかと思います。
(動作しないのだとすれば、やはりネット環境でプロキシが挟まっている可能性が高いです)

**Comment by htakado** [comment]
お世話になります。
ご丁寧にありがとうございます。

pythonでやってみました。
オリジナルの関数にprintを入れて途中もモニタリングしながらやってみましたが、
問題なく翻訳されたようです。

== オリジナルソースにprintを挿入したもの ==

def TranslateByPost(auth_key, text, s_lang, t_lang):
    headers = {'Content-Type': 'application/x-www-form-urlencoded; utf-8'}

    script_url = "https://api-free.deepl.com/v2/translate";
    print('script_url=', script_url)
    params = {
        "auth_key": auth_key,
        "text": text,
        "source_lang": s_lang,
        "target_lang": t_lang
    }
    print('params= ', params)
    encode_data = urllib.parse.urlencode(params).encode('utf-8')
    print('encode_data= ', encode_data)
    req = urllib.request.Request(
        script_url,
        method="POST",
        data=encode_data,
        headers=headers
    )
    print('req= ', req)
    try:
        with urllib.request.urlopen(req) as res:
            print('res= ', res)
            res_json = json.loads(res.read().decode('utf-8'))
            print('res_json= ', res_json)
            return res_json["translations"][0]["text"]
    except urllib.error.HTTPError as e:
        return "翻訳エラー:" + str(e)

    return "翻訳エラー";

answer = TranslateByPost("44e0ac84-XXXXXXXX-f1bd7e3a731c:fx", "Apple", "en", "ja")
print('answer= ', answer)


==　以下コンソール出力 ==

script_url= https://api-free.deepl.com/v2/translate
params=  {'auth_key': '44e0ac84-XXXXXXXXXXXXX-f1bd7e3a731c:fx', 'text': 'Apple', 'source_lang': 'en', 'target_lang': 'ja'}
encode_data=  b'auth_key=44e0ac84-XXXXXXXXXXXX-f1bd7e3a731c%3Afx&text=Apple&source_lang=en&target_lang=ja'
req=  <urllib.request.Request object at 0x000001B0A165BFA0>
res=  <http.client.HTTPResponse object at 0x000001B0A18932E0>
res_json=  {'translations': [{'detected_source_language': 'EN', 'text': 'アップル'}]}
answer=  アップル

python版だと期待した動作をしているようです。

とりあえず、python版で利用させていただこうと思います。
（いまのPCには複数versionのpythonが入っていてそれによるトラブルが想定されるので最終的には、cpp版にしたいのですが、、、）

--追記-- 
pythonで行こうとおもったのですが、zipにhmPython3.dllが入っていないようでした。
→と書いたのですが、cpp版はzipに同梱、python版は別だったのですね。これについては解決しました。

で、python版でやってみると"DLLがロードされていないのにdllfunc関数が使われました"というエラーがでました。
これについては、秀丸自体の使いこなしの問題かなと思うので原因を探してみます！

**Comment by komiyamma** [comment]
python (巣のpythonでの実行)  が上手くいって良かったです。

巣のpythonで上手くいっているならば、少なくとも 「秀丸マクロの runex」 などを使い、
「選択テキストの翻訳結果をアウトプット枠」に出す、くらいは(hmPython3を使わずとも)、出来る状態になっていると思います。

hmPython3 の x64 版は、 秀丸エディタのx64版で動作していると思います(少なくともサイトに上がっているものは64bit秀丸エディタで動作していました)

サイトにも記載がありますが、hmPython3のx64版のインストール先は、「秀丸エディタのディレクトリ(=hidemaru.exeがあるフォルダ」である必要があるので、その点ご注意ください。
（インストール情報が参照とかされているわけではなく、単純にファイルの配置場所だけの問題となります）

**Comment by htakado** [comment]
何度もすみません（泣）

dllfuncについては解決しました。
勝手にhmPython3.dllだけをhidemaruフォルダに置けば良いと思っていたのですが、インストール先自体を指定する必要があったのですね。

ただ、また新たな問題が、、、、
レスポンスとして、「翻訳エラー:HTTP Error 400: 」が帰ってくるようになりました。
pythonで直接やった場合は問題ないのですが、、、、

もしかして、ブラウザが関係したりしますでしょうか？
cpp版と同じような感じになったのでふと思った次第です。
PCには、Edge, chome, Braveが入っているのでそれが関係するのか？とか、、、、

**Comment by komiyamma** [comment]
うーむ、なんとも分からないですねぇ。

例えば、ウィルス対策ソフト等で、(Windows DefenderやMacafee等)、
ファイヤーウォールが hidemaru.exe に対してブロックするという趣旨の所にチェックが入ってしまっているとか。

例えば、なにかふとした拍子に、以前ダイアログ等で「ネットワークへのアクセスを許可しない」を選んでしまい、
それっきりですでに失念とか...

「hidemaruプロセス自体」がネットワークにアクセスするプログラムはマクロってとても少ないので、
このような設定になっていてもずっと気づかなかったかもしれません。
(マクロで通信してるようなものでも、ほとんどものは、裏で別のプロセスが起動して、その結果を受け取っているものが多いため)

**Comment by htakado** [comment]
色々ありがとうございます。
nortonは入っているのですが、確認するときには止めているのと、一応nortonのログを確認してブロックしていないことは確認したのですが、、、（ちなみにWin11 22H2です）

この問題は私の環境の問題のようなので、ぼちぼち調べてみます。
結果が分ったらご報告させていただきます。

ありがとうございました。
